// Code generated by gitpod-log-fields. DO NOT EDIT.

package v1

import (
	logfields "github.com/gitpod-io/flex-api-go/tools/logfields"
)

func (x *GetAccountRequest) LogFields() logfields.Collection {
	return nil
}

func (x *GetAccountResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetAccount())...)
	return fields
}

func (x *DeleteAccountRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "account.id", Value: x.AccountId})
	return fields
}

func (x *DeleteAccountResponse) LogFields() logfields.Collection {
	return nil
}

func (x *Account) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "account.id", Value: x.Id})
	fields.Add(logfields.Extract(x.GetCreatedAt())...)
	fields.Add(logfields.Extract(x.GetUpdatedAt())...)
	return fields
}

func (x *AccountMembership) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "user.id", Value: x.UserId})
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *JoinableOrganization) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *GetSSOLoginURLRequest) LogFields() logfields.Collection {
	return nil
}

func (x *GetSSOLoginURLResponse) LogFields() logfields.Collection {
	return nil
}

func (x *ListLoginProvidersRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	fields.Add(logfields.Extract(x.GetFilter())...)
	return fields
}

func (x *ListLoginProvidersResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *LoginProvider) LogFields() logfields.Collection {
	return nil
}
