// Code generated by gitpod-log-fields. DO NOT EDIT.

package v1

import (
	logfields "github.com/gitpod-io/flex-go/tools/logfields"
)

func (x *ListEditorsRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *ListEditorsResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *GetEditorRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "editor.id", Value: x.Id})
	return fields
}

func (x *GetEditorResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetEditor())...)
	return fields
}

func (x *ResolveEditorURLRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "editor.id", Value: x.EditorId})
	fields.Add(&logfields.Entry{Name: "environment.id", Value: x.EnvironmentId})
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *ResolveEditorURLResponse) LogFields() logfields.Collection {
	return nil
}

func (x *Editor) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "editor.id", Value: x.Id})
	return fields
}
