// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: gitpod/v1/environment_logs.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogSectionOutcome int32

const (
	LogSectionOutcome_LOG_SECTION_OUTCOME_UNSPECIFIED LogSectionOutcome = 0
	LogSectionOutcome_LOG_SECTION_OUTCOME_SUCCESS     LogSectionOutcome = 1
	LogSectionOutcome_LOG_SECTION_OUTCOME_FAILURE     LogSectionOutcome = 2
	LogSectionOutcome_LOG_SECTION_OUTCOME_CANCELLED   LogSectionOutcome = 3
)

// Enum value maps for LogSectionOutcome.
var (
	LogSectionOutcome_name = map[int32]string{
		0: "LOG_SECTION_OUTCOME_UNSPECIFIED",
		1: "LOG_SECTION_OUTCOME_SUCCESS",
		2: "LOG_SECTION_OUTCOME_FAILURE",
		3: "LOG_SECTION_OUTCOME_CANCELLED",
	}
	LogSectionOutcome_value = map[string]int32{
		"LOG_SECTION_OUTCOME_UNSPECIFIED": 0,
		"LOG_SECTION_OUTCOME_SUCCESS":     1,
		"LOG_SECTION_OUTCOME_FAILURE":     2,
		"LOG_SECTION_OUTCOME_CANCELLED":   3,
	}
)

func (x LogSectionOutcome) Enum() *LogSectionOutcome {
	p := new(LogSectionOutcome)
	*p = x
	return p
}

func (x LogSectionOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSectionOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_gitpod_v1_environment_logs_proto_enumTypes[0].Descriptor()
}

func (LogSectionOutcome) Type() protoreflect.EnumType {
	return &file_gitpod_v1_environment_logs_proto_enumTypes[0]
}

func (x LogSectionOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSectionOutcome.Descriptor instead.
func (LogSectionOutcome) EnumDescriptor() ([]byte, []int) {
	return file_gitpod_v1_environment_logs_proto_rawDescGZIP(), []int{0}
}

// CreateLogSection defines the structure of JSON metadata for a create log section entry.
// Example log line:
// [section-create] {"id":"foo","title":"Foo"}
type CreateLogSection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// title is an (optional) human-readable title for the log section.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// continuous indicates if the log section is continuous. Continuous log sections
	// are expected to remain open over the lifetime of an environment, e.g. system logs.
	Continuous bool `protobuf:"varint,3,opt,name=continuous,proto3" json:"continuous,omitempty"`
}

func (x *CreateLogSection) Reset() {
	*x = CreateLogSection{}
	mi := &file_gitpod_v1_environment_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogSection) ProtoMessage() {}

func (x *CreateLogSection) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_environment_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogSection.ProtoReflect.Descriptor instead.
func (*CreateLogSection) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_environment_logs_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLogSection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLogSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLogSection) GetContinuous() bool {
	if x != nil {
		return x.Continuous
	}
	return false
}

// EndLogSection defines the structure of JSON metadata for an end log section entry.
// Example log line:
// [section-end] {"id":"section-id","outcome":"LOG_SECTION_OUTCOME_SUCCESS","secondsElapsed":1.3}
type EndLogSection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// outcome indicates the outcome of the log section.
	Outcome LogSectionOutcome `protobuf:"varint,2,opt,name=outcome,proto3,enum=gitpod.v1.LogSectionOutcome" json:"outcome,omitempty"`
	// seconds_elapsed is the number of seconds that have elapsed since the start of the log section.
	SecondsElapsed float32 `protobuf:"fixed32,3,opt,name=seconds_elapsed,json=secondsElapsed,proto3" json:"seconds_elapsed,omitempty"`
}

func (x *EndLogSection) Reset() {
	*x = EndLogSection{}
	mi := &file_gitpod_v1_environment_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndLogSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndLogSection) ProtoMessage() {}

func (x *EndLogSection) ProtoReflect() protoreflect.Message {
	mi := &file_gitpod_v1_environment_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndLogSection.ProtoReflect.Descriptor instead.
func (*EndLogSection) Descriptor() ([]byte, []int) {
	return file_gitpod_v1_environment_logs_proto_rawDescGZIP(), []int{1}
}

func (x *EndLogSection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EndLogSection) GetOutcome() LogSectionOutcome {
	if x != nil {
		return x.Outcome
	}
	return LogSectionOutcome_LOG_SECTION_OUTCOME_UNSPECIFIED
}

func (x *EndLogSection) GetSecondsElapsed() float32 {
	if x != nil {
		return x.SecondsElapsed
	}
	return 0
}

var File_gitpod_v1_environment_logs_proto protoreflect.FileDescriptor

var file_gitpod_v1_environment_logs_proto_rawDesc = []byte{
	0x0a, 0x20, 0x67, 0x69, 0x74, 0x70, 0x6f, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x67, 0x69, 0x74, 0x70, 0x6f, 0x64, 0x2e, 0x76, 0x31, 0x22, 0x58, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x69,
	0x6e, 0x75, 0x6f, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x6f, 0x75, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x0d, 0x45, 0x6e, 0x64, 0x4c,
	0x6f, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x07, 0x6f, 0x75, 0x74,
	0x63, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x69, 0x74,
	0x70, 0x6f, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x5f, 0x65, 0x6c, 0x61,
	0x70, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x45, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x2a, 0x9d, 0x01, 0x0a, 0x11, 0x4c,
	0x6f, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x1f, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x4f, 0x55, 0x54, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x55, 0x54, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x55, 0x54, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x02, 0x12, 0x21, 0x0a, 0x1d, 0x4c, 0x4f, 0x47, 0x5f, 0x53,
	0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x55, 0x54, 0x43, 0x4f, 0x4d, 0x45, 0x5f, 0x43,
	0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x69, 0x74, 0x70, 0x6f, 0x64, 0x2d,
	0x69, 0x6f, 0x2f, 0x67, 0x69, 0x74, 0x70, 0x6f, 0x64, 0x2d, 0x6e, 0x65, 0x78, 0x74, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gitpod_v1_environment_logs_proto_rawDescOnce sync.Once
	file_gitpod_v1_environment_logs_proto_rawDescData = file_gitpod_v1_environment_logs_proto_rawDesc
)

func file_gitpod_v1_environment_logs_proto_rawDescGZIP() []byte {
	file_gitpod_v1_environment_logs_proto_rawDescOnce.Do(func() {
		file_gitpod_v1_environment_logs_proto_rawDescData = protoimpl.X.CompressGZIP(file_gitpod_v1_environment_logs_proto_rawDescData)
	})
	return file_gitpod_v1_environment_logs_proto_rawDescData
}

var file_gitpod_v1_environment_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gitpod_v1_environment_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gitpod_v1_environment_logs_proto_goTypes = []any{
	(LogSectionOutcome)(0),   // 0: gitpod.v1.LogSectionOutcome
	(*CreateLogSection)(nil), // 1: gitpod.v1.CreateLogSection
	(*EndLogSection)(nil),    // 2: gitpod.v1.EndLogSection
}
var file_gitpod_v1_environment_logs_proto_depIdxs = []int32{
	0, // 0: gitpod.v1.EndLogSection.outcome:type_name -> gitpod.v1.LogSectionOutcome
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gitpod_v1_environment_logs_proto_init() }
func file_gitpod_v1_environment_logs_proto_init() {
	if File_gitpod_v1_environment_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gitpod_v1_environment_logs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gitpod_v1_environment_logs_proto_goTypes,
		DependencyIndexes: file_gitpod_v1_environment_logs_proto_depIdxs,
		EnumInfos:         file_gitpod_v1_environment_logs_proto_enumTypes,
		MessageInfos:      file_gitpod_v1_environment_logs_proto_msgTypes,
	}.Build()
	File_gitpod_v1_environment_logs_proto = out.File
	file_gitpod_v1_environment_logs_proto_rawDesc = nil
	file_gitpod_v1_environment_logs_proto_goTypes = nil
	file_gitpod_v1_environment_logs_proto_depIdxs = nil
}
