// Code generated by gitpod-log-fields. DO NOT EDIT.

package v1

import (
	logfields "github.com/gitpod-io/flex-go/tools/logfields"
)

func (x *InvokeModelRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetAnthropicRequest())...)
	return fields
}

func (x *InvokeModelResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetAnthropicResponse())...)
	return fields
}

func (x *AnthropicRequest) LogFields() logfields.Collection {
	return nil
}

func (x *AnthropicMessage) LogFields() logfields.Collection {
	return nil
}

func (x *AnthropicResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetTimestamp())...)
	return fields
}
