// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gitpod/v1/login_provider.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginProviderKind identifies the provider used to authenticate an account.
type LoginProviderKind int32

const (
	LoginProviderKind_LOGIN_PROVIDER_KIND_UNSPECIFIED LoginProviderKind = 0
	LoginProviderKind_LOGIN_PROVIDER_KIND_SSO         LoginProviderKind = 1
	LoginProviderKind_LOGIN_PROVIDER_KIND_GITHUB      LoginProviderKind = 2
	LoginProviderKind_LOGIN_PROVIDER_KIND_GOOGLE      LoginProviderKind = 3
	LoginProviderKind_LOGIN_PROVIDER_KIND_MAGICLINK   LoginProviderKind = 4
)

// Enum value maps for LoginProviderKind.
var (
	LoginProviderKind_name = map[int32]string{
		0: "LOGIN_PROVIDER_KIND_UNSPECIFIED",
		1: "LOGIN_PROVIDER_KIND_SSO",
		2: "LOGIN_PROVIDER_KIND_GITHUB",
		3: "LOGIN_PROVIDER_KIND_GOOGLE",
		4: "LOGIN_PROVIDER_KIND_MAGICLINK",
	}
	LoginProviderKind_value = map[string]int32{
		"LOGIN_PROVIDER_KIND_UNSPECIFIED": 0,
		"LOGIN_PROVIDER_KIND_SSO":         1,
		"LOGIN_PROVIDER_KIND_GITHUB":      2,
		"LOGIN_PROVIDER_KIND_GOOGLE":      3,
		"LOGIN_PROVIDER_KIND_MAGICLINK":   4,
	}
)

func (x LoginProviderKind) Enum() *LoginProviderKind {
	p := new(LoginProviderKind)
	*p = x
	return p
}

func (x LoginProviderKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginProviderKind) Descriptor() protoreflect.EnumDescriptor {
	return file_gitpod_v1_login_provider_proto_enumTypes[0].Descriptor()
}

func (LoginProviderKind) Type() protoreflect.EnumType {
	return &file_gitpod_v1_login_provider_proto_enumTypes[0]
}

func (x LoginProviderKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginProviderKind.Descriptor instead.
func (LoginProviderKind) EnumDescriptor() ([]byte, []int) {
	return file_gitpod_v1_login_provider_proto_rawDescGZIP(), []int{0}
}

var File_gitpod_v1_login_provider_proto protoreflect.FileDescriptor

const file_gitpod_v1_login_provider_proto_rawDesc = "" +
	"\n" +
	"\x1egitpod/v1/login_provider.proto\x12\tgitpod.v1*\xb8\x01\n" +
	"\x11LoginProviderKind\x12#\n" +
	"\x1fLOGIN_PROVIDER_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17LOGIN_PROVIDER_KIND_SSO\x10\x01\x12\x1e\n" +
	"\x1aLOGIN_PROVIDER_KIND_GITHUB\x10\x02\x12\x1e\n" +
	"\x1aLOGIN_PROVIDER_KIND_GOOGLE\x10\x03\x12!\n" +
	"\x1dLOGIN_PROVIDER_KIND_MAGICLINK\x10\x04B'Z%github.com/gitpod-io/gitpod-sdk-go/v1b\x06proto3"

var (
	file_gitpod_v1_login_provider_proto_rawDescOnce sync.Once
	file_gitpod_v1_login_provider_proto_rawDescData []byte
)

func file_gitpod_v1_login_provider_proto_rawDescGZIP() []byte {
	file_gitpod_v1_login_provider_proto_rawDescOnce.Do(func() {
		file_gitpod_v1_login_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitpod_v1_login_provider_proto_rawDesc), len(file_gitpod_v1_login_provider_proto_rawDesc)))
	})
	return file_gitpod_v1_login_provider_proto_rawDescData
}

var file_gitpod_v1_login_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gitpod_v1_login_provider_proto_goTypes = []any{
	(LoginProviderKind)(0), // 0: gitpod.v1.LoginProviderKind
}
var file_gitpod_v1_login_provider_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gitpod_v1_login_provider_proto_init() }
func file_gitpod_v1_login_provider_proto_init() {
	if File_gitpod_v1_login_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitpod_v1_login_provider_proto_rawDesc), len(file_gitpod_v1_login_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gitpod_v1_login_provider_proto_goTypes,
		DependencyIndexes: file_gitpod_v1_login_provider_proto_depIdxs,
		EnumInfos:         file_gitpod_v1_login_provider_proto_enumTypes,
	}.Build()
	File_gitpod_v1_login_provider_proto = out.File
	file_gitpod_v1_login_provider_proto_goTypes = nil
	file_gitpod_v1_login_provider_proto_depIdxs = nil
}
