// Code generated by gitpod-log-fields. DO NOT EDIT.

package v1

import (
	logfields "github.com/gitpod-io/flex-sdk-go/tools/logfields"
)

func (x *UpdateOrganizationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	fields.Add(logfields.Extract(x.GetInviteDomains())...)
	return fields
}

func (x *UpdateOrganizationResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetOrganization())...)
	return fields
}

func (x *CreateOrganizationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.name", Value: x.Name})
	return fields
}

func (x *CreateOrganizationResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetOrganization())...)
	fields.Add(logfields.Extract(x.GetMember())...)
	return fields
}

func (x *JoinOrganizationRequest) LogFields() logfields.Collection {
	return nil
}

func (x *JoinOrganizationResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetMember())...)
	return fields
}

func (x *LeaveOrganizationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "user.id", Value: x.UserId})
	return fields
}

func (x *LeaveOrganizationResponse) LogFields() logfields.Collection {
	return nil
}

func (x *GetOrganizationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *GetOrganizationResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetOrganization())...)
	return fields
}

func (x *ListOrganizationsRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *ListOrganizationsResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *DeleteOrganizationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *DeleteOrganizationResponse) LogFields() logfields.Collection {
	return nil
}

func (x *ListMembersRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *ListMembersResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *SetRoleRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	fields.Add(&logfields.Entry{Name: "user.id", Value: x.UserId})
	return fields
}

func (x *SetRoleResponse) LogFields() logfields.Collection {
	return nil
}

func (x *GetOrganizationInviteRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *GetOrganizationInviteResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetInvite())...)
	return fields
}

func (x *OrganizationInvite) LogFields() logfields.Collection {
	return nil
}

func (x *CreateOrganizationInviteRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *CreateOrganizationInviteResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetInvite())...)
	return fields
}

func (x *GetOrganizationInviteSummaryRequest) LogFields() logfields.Collection {
	return nil
}

func (x *GetOrganizationInviteSummaryResponse) LogFields() logfields.Collection {
	return nil
}

func (x *Organization) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.Id})
	fields.Add(logfields.Extract(x.GetCreatedAt())...)
	fields.Add(logfields.Extract(x.GetUpdatedAt())...)
	fields.Add(logfields.Extract(x.GetInviteDomains())...)
	return fields
}

func (x *OrganizationMember) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetMemberSince())...)
	return fields
}

func (x *InviteDomains) LogFields() logfields.Collection {
	return nil
}

func (x *CreateSSOConfigurationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *CreateSSOConfigurationResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetSsoConfiguration())...)
	return fields
}

func (x *SSOConfiguration) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *GetSSOConfigurationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "sso_configuration.id", Value: x.SsoConfigurationId})
	return fields
}

func (x *GetSSOConfigurationResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetSsoConfiguration())...)
	return fields
}

func (x *ListSSOConfigurationsRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	fields.Add(&logfields.Entry{Name: "organization.id", Value: x.OrganizationId})
	return fields
}

func (x *ListSSOConfigurationsResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *UpdateSSOConfigurationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "sso_configuration.id", Value: x.SsoConfigurationId})
	return fields
}

func (x *UpdateSSOConfigurationResponse) LogFields() logfields.Collection {
	return nil
}

func (x *DeleteSSOConfigurationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "sso_configuration.id", Value: x.SsoConfigurationId})
	return fields
}

func (x *DeleteSSOConfigurationResponse) LogFields() logfields.Collection {
	return nil
}
