// Code generated by gitpod-log-fields. DO NOT EDIT.

package v1

import (
	logfields "github.com/gitpod-io/flex-api-go/tools/logfields"
)

func (x *Owner) LogFields() logfields.Collection {
	return nil
}
