// Code generated by gitpod-log-fields. DO NOT EDIT.

package v1

import (
	logfields "github.com/gitpod-io/flex-sdk-go/tools/logfields"
)

func (x *SignupRequest) LogFields() logfields.Collection {
	return nil
}

func (x *SignupResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *MarkRunnerActiveRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *MarkRunnerActiveResponse) LogFields() logfields.Collection {
	return nil
}

func (x *ListRunnerEnvironmentsRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *RunnerEnvironment) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "environment.id", Value: x.Id})
	fields.Add(logfields.Extract(x.GetMetadata())...)
	fields.Add(logfields.Extract(x.GetSpec())...)
	fields.Add(logfields.Extract(x.GetActivitySignal())...)
	return fields
}

func (x *ListRunnerEnvironmentsResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *GetRunnerEnvironmentRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	fields.Add(&logfields.Entry{Name: "environment.id", Value: x.EnvironmentId})
	return fields
}

func (x *GetRunnerEnvironmentResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetEnvironment())...)
	return fields
}

func (x *UpdateRunnerEnvironmentStatusRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	fields.Add(&logfields.Entry{Name: "environment.id", Value: x.EnvironmentId})
	fields.Add(logfields.Extract(x.GetStatus())...)
	return fields
}

func (x *UpdateRunnerEnvironmentStatusResponse) LogFields() logfields.Collection {
	return nil
}

func (x *UpdateRunnerStatusRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *UpdateRunnerStatusResponse) LogFields() logfields.Collection {
	return nil
}

func (x *UpdateRunnerConfigurationSchemaRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	fields.Add(logfields.Extract(x.GetConfigSchema())...)
	return fields
}

func (x *UpdateRunnerConfigurationSchemaResponse) LogFields() logfields.Collection {
	return nil
}

func (x *GetHostAuthenticationTokenValueRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *GetHostAuthenticationTokenValueResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetExpiresAt())...)
	return fields
}

func (x *ListRunnerEnvironmentClassesRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	fields.Add(logfields.Extract(x.GetFilter())...)
	return fields
}

func (x *ListRunnerEnvironmentClassesResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *ListRunnerSCMIntegrationsRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	fields.Add(logfields.Extract(x.GetFilter())...)
	return fields
}

func (x *ListRunnerSCMIntegrationsResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *WatchRequestsRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *WatchRequestsResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "request.id", Value: x.RequestId})
	fields.Add(logfields.Extract(x.GetEventEnvironmentSpecChange())...)
	fields.Add(logfields.Extract(x.GetEventEnvironmentMarkedActive())...)
	fields.Add(logfields.Extract(x.GetEventScmIntegrationChange())...)
	fields.Add(logfields.Extract(x.GetEventHostAuthenticationTokenDeleted())...)
	fields.Add(logfields.Extract(x.GetCallParseContext())...)
	fields.Add(logfields.Extract(x.GetCallPing())...)
	fields.Add(logfields.Extract(x.GetCallCheckAuthenticationForHost())...)
	fields.Add(logfields.Extract(x.GetCallValidateConfig())...)
	return fields
}

func (x *SendResponseRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	fields.Add(&logfields.Entry{Name: "request.id", Value: x.RequestId})
	fields.Add(logfields.Extract(x.GetError())...)
	fields.Add(logfields.Extract(x.GetCallParseContext())...)
	fields.Add(logfields.Extract(x.GetCallPing())...)
	fields.Add(logfields.Extract(x.GetCallCheckAuthenticationForHost())...)
	fields.Add(logfields.Extract(x.GetCallValidateConfig())...)
	return fields
}

func (x *SendResponseResponse) LogFields() logfields.Collection {
	return nil
}

func (x *EventEnvironmentSpecChange) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "environment.id", Value: x.EnvironmentId})
	return fields
}

func (x *EventEnvironmentMarkedActive) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "environment.id", Value: x.EnvironmentId})
	return fields
}

func (x *EventSCMIntegrationChange) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "scmintegration.id", Value: x.ScmIntegrationId})
	return fields
}

func (x *EventHostAuthenticationTokenDeleted) LogFields() logfields.Collection {
	return nil
}

func (x *CallParseContext) LogFields() logfields.Collection {
	return nil
}

func (x *CallPing) LogFields() logfields.Collection {
	return nil
}

func (x *CallCheckAuthenticationForHost) LogFields() logfields.Collection {
	return nil
}

func (x *CallValidateConfig) LogFields() logfields.Collection {
	return nil
}

func (x *GetLatestVersionRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *GetLatestVersionResponse) LogFields() logfields.Collection {
	return nil
}
