// Code generated by gitpod-log-fields. DO NOT EDIT.

package v1

import (
	logfields "github.com/gitpod-io/flex-sdk-go/tools/logfields"
)

func (x *CreateHostAuthenticationTokenRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	fields.Add(&logfields.Entry{Name: "user.id", Value: x.UserId})
	fields.Add(logfields.Extract(x.GetExpiresAt())...)
	return fields
}

func (x *CreateHostAuthenticationTokenResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetToken())...)
	return fields
}

func (x *HostAuthenticationToken) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetExpiresAt())...)
	return fields
}

func (x *GetHostAuthenticationTokenRequest) LogFields() logfields.Collection {
	return nil
}

func (x *GetHostAuthenticationTokenResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetToken())...)
	return fields
}

func (x *ListHostAuthenticationTokensRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	fields.Add(logfields.Extract(x.GetFilter())...)
	return fields
}

func (x *ListHostAuthenticationTokensResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *UpdateHostAuthenticationTokenRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetExpiresAt())...)
	return fields
}

func (x *UpdateHostAuthenticationTokenResponse) LogFields() logfields.Collection {
	return nil
}

func (x *DeleteHostAuthenticationTokenRequest) LogFields() logfields.Collection {
	return nil
}

func (x *DeleteHostAuthenticationTokenResponse) LogFields() logfields.Collection {
	return nil
}

func (x *FieldValue) LogFields() logfields.Collection {
	return nil
}

func (x *FieldValueUpdate) LogFields() logfields.Collection {
	return nil
}

func (x *GetRunnerConfigurationSchemaRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *GetRunnerConfigurationSchemaResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetSchema())...)
	return fields
}

func (x *CreateSCMIntegrationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	fields.Add(&logfields.Entry{Name: "scm.id", Value: x.ScmId})
	return fields
}

func (x *CreateSCMIntegrationResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "scmintegration.id", Value: x.Id})
	return fields
}

func (x *SCMIntegrationOAuthConfig) LogFields() logfields.Collection {
	return nil
}

func (x *SCMIntegration) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "scmintegration.id", Value: x.Id})
	fields.Add(&logfields.Entry{Name: "scm.id", Value: x.ScmId})
	fields.Add(logfields.Extract(x.GetOauth())...)
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *GetSCMIntegrationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "scmintegration.id", Value: x.Id})
	return fields
}

func (x *GetSCMIntegrationResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetIntegration())...)
	return fields
}

func (x *ListSCMIntegrationsRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	fields.Add(logfields.Extract(x.GetFilter())...)
	return fields
}

func (x *ListSCMIntegrationsResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *UpdateSCMIntegrationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "scmintegration.id", Value: x.Id})
	return fields
}

func (x *UpdateSCMIntegrationResponse) LogFields() logfields.Collection {
	return nil
}

func (x *DeleteSCMIntegrationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "scmintegration.id", Value: x.Id})
	return fields
}

func (x *DeleteSCMIntegrationResponse) LogFields() logfields.Collection {
	return nil
}

func (x *EnvironmentClass) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "envclass.id", Value: x.Id})
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *CreateEnvironmentClassRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	return fields
}

func (x *CreateEnvironmentClassResponse) LogFields() logfields.Collection {
	return nil
}

func (x *GetEnvironmentClassRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "environment_class.id", Value: x.EnvironmentClassId})
	return fields
}

func (x *GetEnvironmentClassResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetEnvironmentClass())...)
	return fields
}

func (x *ListEnvironmentClassesRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	fields.Add(logfields.Extract(x.GetFilter())...)
	return fields
}

func (x *ListEnvironmentClassesResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetPagination())...)
	return fields
}

func (x *UpdateEnvironmentClassRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "environment_class.id", Value: x.EnvironmentClassId})
	return fields
}

func (x *UpdateEnvironmentClassResponse) LogFields() logfields.Collection {
	return nil
}

func (x *ValidateRunnerConfigurationRequest) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(&logfields.Entry{Name: "runner.id", Value: x.RunnerId})
	fields.Add(logfields.Extract(x.GetEnvironmentClass())...)
	fields.Add(logfields.Extract(x.GetScmIntegration())...)
	return fields
}

func (x *FieldValidationError) LogFields() logfields.Collection {
	return nil
}

func (x *EnvironmentClassValidationResult) LogFields() logfields.Collection {
	return nil
}

func (x *SCMIntegrationValidationResult) LogFields() logfields.Collection {
	return nil
}

func (x *ValidateRunnerConfigurationResponse) LogFields() logfields.Collection {
	if x == nil {
		return nil
	}

	var fields logfields.Collection
	fields.Add(logfields.Extract(x.GetEnvironmentClass())...)
	fields.Add(logfields.Extract(x.GetScmIntegration())...)
	return fields
}

func (x *RunnerConfigurationSchema) LogFields() logfields.Collection {
	return nil
}
