// Code generated by MockGen. DO NOT EDIT.
// Source: v1/v1connect/billing.connect.go
//
// Generated by this command:
//
//	mockgen -source=v1/v1connect/billing.connect.go -destination=internal/raw/mock/billing.connect_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	v1 "github.com/gitpod-io/gitpod-sdk-go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockBillingServiceClient is a mock of BillingServiceClient interface.
type MockBillingServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBillingServiceClientMockRecorder
	isgomock struct{}
}

// MockBillingServiceClientMockRecorder is the mock recorder for MockBillingServiceClient.
type MockBillingServiceClientMockRecorder struct {
	mock *MockBillingServiceClient
}

// NewMockBillingServiceClient creates a new mock instance.
func NewMockBillingServiceClient(ctrl *gomock.Controller) *MockBillingServiceClient {
	mock := &MockBillingServiceClient{ctrl: ctrl}
	mock.recorder = &MockBillingServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingServiceClient) EXPECT() *MockBillingServiceClientMockRecorder {
	return m.recorder
}

// CreateTeamCreditAllocation mocks base method.
func (m *MockBillingServiceClient) CreateTeamCreditAllocation(arg0 context.Context, arg1 *connect.Request[v1.CreateTeamCreditAllocationRequest]) (*connect.Response[v1.CreateTeamCreditAllocationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeamCreditAllocation", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateTeamCreditAllocationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeamCreditAllocation indicates an expected call of CreateTeamCreditAllocation.
func (mr *MockBillingServiceClientMockRecorder) CreateTeamCreditAllocation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeamCreditAllocation", reflect.TypeOf((*MockBillingServiceClient)(nil).CreateTeamCreditAllocation), arg0, arg1)
}

// DeleteEnterpriseAIUserBudgetPolicy mocks base method.
func (m *MockBillingServiceClient) DeleteEnterpriseAIUserBudgetPolicy(arg0 context.Context, arg1 *connect.Request[v1.DeleteEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.DeleteEnterpriseAIUserBudgetPolicyResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEnterpriseAIUserBudgetPolicy", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteEnterpriseAIUserBudgetPolicyResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEnterpriseAIUserBudgetPolicy indicates an expected call of DeleteEnterpriseAIUserBudgetPolicy.
func (mr *MockBillingServiceClientMockRecorder) DeleteEnterpriseAIUserBudgetPolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEnterpriseAIUserBudgetPolicy", reflect.TypeOf((*MockBillingServiceClient)(nil).DeleteEnterpriseAIUserBudgetPolicy), arg0, arg1)
}

// DeleteTeamCreditAllocation mocks base method.
func (m *MockBillingServiceClient) DeleteTeamCreditAllocation(arg0 context.Context, arg1 *connect.Request[v1.DeleteTeamCreditAllocationRequest]) (*connect.Response[v1.DeleteTeamCreditAllocationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeamCreditAllocation", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteTeamCreditAllocationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTeamCreditAllocation indicates an expected call of DeleteTeamCreditAllocation.
func (mr *MockBillingServiceClientMockRecorder) DeleteTeamCreditAllocation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeamCreditAllocation", reflect.TypeOf((*MockBillingServiceClient)(nil).DeleteTeamCreditAllocation), arg0, arg1)
}

// GetCreditUsageExport mocks base method.
func (m *MockBillingServiceClient) GetCreditUsageExport(arg0 context.Context, arg1 *connect.Request[v1.GetCreditUsageExportRequest]) (*connect.Response[v1.GetCreditUsageExportResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreditUsageExport", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetCreditUsageExportResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreditUsageExport indicates an expected call of GetCreditUsageExport.
func (mr *MockBillingServiceClientMockRecorder) GetCreditUsageExport(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreditUsageExport", reflect.TypeOf((*MockBillingServiceClient)(nil).GetCreditUsageExport), arg0, arg1)
}

// GetCreditUsageReport mocks base method.
func (m *MockBillingServiceClient) GetCreditUsageReport(arg0 context.Context, arg1 *connect.Request[v1.GetCreditUsageReportRequest]) (*connect.Response[v1.GetCreditUsageReportResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreditUsageReport", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetCreditUsageReportResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreditUsageReport indicates an expected call of GetCreditUsageReport.
func (mr *MockBillingServiceClientMockRecorder) GetCreditUsageReport(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreditUsageReport", reflect.TypeOf((*MockBillingServiceClient)(nil).GetCreditUsageReport), arg0, arg1)
}

// GetCumulativeCreditUsage mocks base method.
func (m *MockBillingServiceClient) GetCumulativeCreditUsage(arg0 context.Context, arg1 *connect.Request[v1.GetCumulativeCreditUsageRequest]) (*connect.Response[v1.GetCumulativeCreditUsageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCumulativeCreditUsage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetCumulativeCreditUsageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCumulativeCreditUsage indicates an expected call of GetCumulativeCreditUsage.
func (mr *MockBillingServiceClientMockRecorder) GetCumulativeCreditUsage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCumulativeCreditUsage", reflect.TypeOf((*MockBillingServiceClient)(nil).GetCumulativeCreditUsage), arg0, arg1)
}

// GetEnterpriseAIUsageSummary mocks base method.
func (m *MockBillingServiceClient) GetEnterpriseAIUsageSummary(arg0 context.Context, arg1 *connect.Request[v1.GetEnterpriseAIUsageSummaryRequest]) (*connect.Response[v1.GetEnterpriseAIUsageSummaryResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterpriseAIUsageSummary", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetEnterpriseAIUsageSummaryResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseAIUsageSummary indicates an expected call of GetEnterpriseAIUsageSummary.
func (mr *MockBillingServiceClientMockRecorder) GetEnterpriseAIUsageSummary(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseAIUsageSummary", reflect.TypeOf((*MockBillingServiceClient)(nil).GetEnterpriseAIUsageSummary), arg0, arg1)
}

// GetEnterpriseAIUsageTimeSeries mocks base method.
func (m *MockBillingServiceClient) GetEnterpriseAIUsageTimeSeries(arg0 context.Context, arg1 *connect.Request[v1.GetEnterpriseAIUsageTimeSeriesRequest]) (*connect.Response[v1.GetEnterpriseAIUsageTimeSeriesResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterpriseAIUsageTimeSeries", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetEnterpriseAIUsageTimeSeriesResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseAIUsageTimeSeries indicates an expected call of GetEnterpriseAIUsageTimeSeries.
func (mr *MockBillingServiceClientMockRecorder) GetEnterpriseAIUsageTimeSeries(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseAIUsageTimeSeries", reflect.TypeOf((*MockBillingServiceClient)(nil).GetEnterpriseAIUsageTimeSeries), arg0, arg1)
}

// GetEnterpriseAIUserBudgetPolicy mocks base method.
func (m *MockBillingServiceClient) GetEnterpriseAIUserBudgetPolicy(arg0 context.Context, arg1 *connect.Request[v1.GetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.GetEnterpriseAIUserBudgetPolicyResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterpriseAIUserBudgetPolicy", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetEnterpriseAIUserBudgetPolicyResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseAIUserBudgetPolicy indicates an expected call of GetEnterpriseAIUserBudgetPolicy.
func (mr *MockBillingServiceClientMockRecorder) GetEnterpriseAIUserBudgetPolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseAIUserBudgetPolicy", reflect.TypeOf((*MockBillingServiceClient)(nil).GetEnterpriseAIUserBudgetPolicy), arg0, arg1)
}

// GetTeamCreditAllocation mocks base method.
func (m *MockBillingServiceClient) GetTeamCreditAllocation(arg0 context.Context, arg1 *connect.Request[v1.GetTeamCreditAllocationRequest]) (*connect.Response[v1.GetTeamCreditAllocationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamCreditAllocation", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetTeamCreditAllocationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamCreditAllocation indicates an expected call of GetTeamCreditAllocation.
func (mr *MockBillingServiceClientMockRecorder) GetTeamCreditAllocation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamCreditAllocation", reflect.TypeOf((*MockBillingServiceClient)(nil).GetTeamCreditAllocation), arg0, arg1)
}

// ListEnterpriseAITeamUsage mocks base method.
func (m *MockBillingServiceClient) ListEnterpriseAITeamUsage(arg0 context.Context, arg1 *connect.Request[v1.ListEnterpriseAITeamUsageRequest]) (*connect.Response[v1.ListEnterpriseAITeamUsageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnterpriseAITeamUsage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListEnterpriseAITeamUsageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnterpriseAITeamUsage indicates an expected call of ListEnterpriseAITeamUsage.
func (mr *MockBillingServiceClientMockRecorder) ListEnterpriseAITeamUsage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnterpriseAITeamUsage", reflect.TypeOf((*MockBillingServiceClient)(nil).ListEnterpriseAITeamUsage), arg0, arg1)
}

// ListEnterpriseAIUserUsage mocks base method.
func (m *MockBillingServiceClient) ListEnterpriseAIUserUsage(arg0 context.Context, arg1 *connect.Request[v1.ListEnterpriseAIUserUsageRequest]) (*connect.Response[v1.ListEnterpriseAIUserUsageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnterpriseAIUserUsage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListEnterpriseAIUserUsageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnterpriseAIUserUsage indicates an expected call of ListEnterpriseAIUserUsage.
func (mr *MockBillingServiceClientMockRecorder) ListEnterpriseAIUserUsage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnterpriseAIUserUsage", reflect.TypeOf((*MockBillingServiceClient)(nil).ListEnterpriseAIUserUsage), arg0, arg1)
}

// ListEnterpriseUserCreditUsage mocks base method.
func (m *MockBillingServiceClient) ListEnterpriseUserCreditUsage(arg0 context.Context, arg1 *connect.Request[v1.ListEnterpriseUserCreditUsageRequest]) (*connect.Response[v1.ListEnterpriseUserCreditUsageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnterpriseUserCreditUsage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListEnterpriseUserCreditUsageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnterpriseUserCreditUsage indicates an expected call of ListEnterpriseUserCreditUsage.
func (mr *MockBillingServiceClientMockRecorder) ListEnterpriseUserCreditUsage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnterpriseUserCreditUsage", reflect.TypeOf((*MockBillingServiceClient)(nil).ListEnterpriseUserCreditUsage), arg0, arg1)
}

// SetEnterpriseAIUserBudgetPolicy mocks base method.
func (m *MockBillingServiceClient) SetEnterpriseAIUserBudgetPolicy(arg0 context.Context, arg1 *connect.Request[v1.SetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.SetEnterpriseAIUserBudgetPolicyResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnterpriseAIUserBudgetPolicy", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.SetEnterpriseAIUserBudgetPolicyResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEnterpriseAIUserBudgetPolicy indicates an expected call of SetEnterpriseAIUserBudgetPolicy.
func (mr *MockBillingServiceClientMockRecorder) SetEnterpriseAIUserBudgetPolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnterpriseAIUserBudgetPolicy", reflect.TypeOf((*MockBillingServiceClient)(nil).SetEnterpriseAIUserBudgetPolicy), arg0, arg1)
}

// UpdateTeamCreditAllocation mocks base method.
func (m *MockBillingServiceClient) UpdateTeamCreditAllocation(arg0 context.Context, arg1 *connect.Request[v1.UpdateTeamCreditAllocationRequest]) (*connect.Response[v1.UpdateTeamCreditAllocationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeamCreditAllocation", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateTeamCreditAllocationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTeamCreditAllocation indicates an expected call of UpdateTeamCreditAllocation.
func (mr *MockBillingServiceClientMockRecorder) UpdateTeamCreditAllocation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeamCreditAllocation", reflect.TypeOf((*MockBillingServiceClient)(nil).UpdateTeamCreditAllocation), arg0, arg1)
}

// MockBillingServiceHandler is a mock of BillingServiceHandler interface.
type MockBillingServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockBillingServiceHandlerMockRecorder
	isgomock struct{}
}

// MockBillingServiceHandlerMockRecorder is the mock recorder for MockBillingServiceHandler.
type MockBillingServiceHandlerMockRecorder struct {
	mock *MockBillingServiceHandler
}

// NewMockBillingServiceHandler creates a new mock instance.
func NewMockBillingServiceHandler(ctrl *gomock.Controller) *MockBillingServiceHandler {
	mock := &MockBillingServiceHandler{ctrl: ctrl}
	mock.recorder = &MockBillingServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingServiceHandler) EXPECT() *MockBillingServiceHandlerMockRecorder {
	return m.recorder
}

// CreateTeamCreditAllocation mocks base method.
func (m *MockBillingServiceHandler) CreateTeamCreditAllocation(arg0 context.Context, arg1 *connect.Request[v1.CreateTeamCreditAllocationRequest]) (*connect.Response[v1.CreateTeamCreditAllocationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeamCreditAllocation", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.CreateTeamCreditAllocationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeamCreditAllocation indicates an expected call of CreateTeamCreditAllocation.
func (mr *MockBillingServiceHandlerMockRecorder) CreateTeamCreditAllocation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeamCreditAllocation", reflect.TypeOf((*MockBillingServiceHandler)(nil).CreateTeamCreditAllocation), arg0, arg1)
}

// DeleteEnterpriseAIUserBudgetPolicy mocks base method.
func (m *MockBillingServiceHandler) DeleteEnterpriseAIUserBudgetPolicy(arg0 context.Context, arg1 *connect.Request[v1.DeleteEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.DeleteEnterpriseAIUserBudgetPolicyResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEnterpriseAIUserBudgetPolicy", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteEnterpriseAIUserBudgetPolicyResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEnterpriseAIUserBudgetPolicy indicates an expected call of DeleteEnterpriseAIUserBudgetPolicy.
func (mr *MockBillingServiceHandlerMockRecorder) DeleteEnterpriseAIUserBudgetPolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEnterpriseAIUserBudgetPolicy", reflect.TypeOf((*MockBillingServiceHandler)(nil).DeleteEnterpriseAIUserBudgetPolicy), arg0, arg1)
}

// DeleteTeamCreditAllocation mocks base method.
func (m *MockBillingServiceHandler) DeleteTeamCreditAllocation(arg0 context.Context, arg1 *connect.Request[v1.DeleteTeamCreditAllocationRequest]) (*connect.Response[v1.DeleteTeamCreditAllocationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeamCreditAllocation", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.DeleteTeamCreditAllocationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTeamCreditAllocation indicates an expected call of DeleteTeamCreditAllocation.
func (mr *MockBillingServiceHandlerMockRecorder) DeleteTeamCreditAllocation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeamCreditAllocation", reflect.TypeOf((*MockBillingServiceHandler)(nil).DeleteTeamCreditAllocation), arg0, arg1)
}

// GetCreditUsageExport mocks base method.
func (m *MockBillingServiceHandler) GetCreditUsageExport(arg0 context.Context, arg1 *connect.Request[v1.GetCreditUsageExportRequest]) (*connect.Response[v1.GetCreditUsageExportResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreditUsageExport", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetCreditUsageExportResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreditUsageExport indicates an expected call of GetCreditUsageExport.
func (mr *MockBillingServiceHandlerMockRecorder) GetCreditUsageExport(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreditUsageExport", reflect.TypeOf((*MockBillingServiceHandler)(nil).GetCreditUsageExport), arg0, arg1)
}

// GetCreditUsageReport mocks base method.
func (m *MockBillingServiceHandler) GetCreditUsageReport(arg0 context.Context, arg1 *connect.Request[v1.GetCreditUsageReportRequest]) (*connect.Response[v1.GetCreditUsageReportResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreditUsageReport", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetCreditUsageReportResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreditUsageReport indicates an expected call of GetCreditUsageReport.
func (mr *MockBillingServiceHandlerMockRecorder) GetCreditUsageReport(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreditUsageReport", reflect.TypeOf((*MockBillingServiceHandler)(nil).GetCreditUsageReport), arg0, arg1)
}

// GetCumulativeCreditUsage mocks base method.
func (m *MockBillingServiceHandler) GetCumulativeCreditUsage(arg0 context.Context, arg1 *connect.Request[v1.GetCumulativeCreditUsageRequest]) (*connect.Response[v1.GetCumulativeCreditUsageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCumulativeCreditUsage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetCumulativeCreditUsageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCumulativeCreditUsage indicates an expected call of GetCumulativeCreditUsage.
func (mr *MockBillingServiceHandlerMockRecorder) GetCumulativeCreditUsage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCumulativeCreditUsage", reflect.TypeOf((*MockBillingServiceHandler)(nil).GetCumulativeCreditUsage), arg0, arg1)
}

// GetEnterpriseAIUsageSummary mocks base method.
func (m *MockBillingServiceHandler) GetEnterpriseAIUsageSummary(arg0 context.Context, arg1 *connect.Request[v1.GetEnterpriseAIUsageSummaryRequest]) (*connect.Response[v1.GetEnterpriseAIUsageSummaryResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterpriseAIUsageSummary", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetEnterpriseAIUsageSummaryResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseAIUsageSummary indicates an expected call of GetEnterpriseAIUsageSummary.
func (mr *MockBillingServiceHandlerMockRecorder) GetEnterpriseAIUsageSummary(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseAIUsageSummary", reflect.TypeOf((*MockBillingServiceHandler)(nil).GetEnterpriseAIUsageSummary), arg0, arg1)
}

// GetEnterpriseAIUsageTimeSeries mocks base method.
func (m *MockBillingServiceHandler) GetEnterpriseAIUsageTimeSeries(arg0 context.Context, arg1 *connect.Request[v1.GetEnterpriseAIUsageTimeSeriesRequest]) (*connect.Response[v1.GetEnterpriseAIUsageTimeSeriesResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterpriseAIUsageTimeSeries", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetEnterpriseAIUsageTimeSeriesResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseAIUsageTimeSeries indicates an expected call of GetEnterpriseAIUsageTimeSeries.
func (mr *MockBillingServiceHandlerMockRecorder) GetEnterpriseAIUsageTimeSeries(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseAIUsageTimeSeries", reflect.TypeOf((*MockBillingServiceHandler)(nil).GetEnterpriseAIUsageTimeSeries), arg0, arg1)
}

// GetEnterpriseAIUserBudgetPolicy mocks base method.
func (m *MockBillingServiceHandler) GetEnterpriseAIUserBudgetPolicy(arg0 context.Context, arg1 *connect.Request[v1.GetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.GetEnterpriseAIUserBudgetPolicyResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnterpriseAIUserBudgetPolicy", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetEnterpriseAIUserBudgetPolicyResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnterpriseAIUserBudgetPolicy indicates an expected call of GetEnterpriseAIUserBudgetPolicy.
func (mr *MockBillingServiceHandlerMockRecorder) GetEnterpriseAIUserBudgetPolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnterpriseAIUserBudgetPolicy", reflect.TypeOf((*MockBillingServiceHandler)(nil).GetEnterpriseAIUserBudgetPolicy), arg0, arg1)
}

// GetTeamCreditAllocation mocks base method.
func (m *MockBillingServiceHandler) GetTeamCreditAllocation(arg0 context.Context, arg1 *connect.Request[v1.GetTeamCreditAllocationRequest]) (*connect.Response[v1.GetTeamCreditAllocationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamCreditAllocation", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.GetTeamCreditAllocationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamCreditAllocation indicates an expected call of GetTeamCreditAllocation.
func (mr *MockBillingServiceHandlerMockRecorder) GetTeamCreditAllocation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamCreditAllocation", reflect.TypeOf((*MockBillingServiceHandler)(nil).GetTeamCreditAllocation), arg0, arg1)
}

// ListEnterpriseAITeamUsage mocks base method.
func (m *MockBillingServiceHandler) ListEnterpriseAITeamUsage(arg0 context.Context, arg1 *connect.Request[v1.ListEnterpriseAITeamUsageRequest]) (*connect.Response[v1.ListEnterpriseAITeamUsageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnterpriseAITeamUsage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListEnterpriseAITeamUsageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnterpriseAITeamUsage indicates an expected call of ListEnterpriseAITeamUsage.
func (mr *MockBillingServiceHandlerMockRecorder) ListEnterpriseAITeamUsage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnterpriseAITeamUsage", reflect.TypeOf((*MockBillingServiceHandler)(nil).ListEnterpriseAITeamUsage), arg0, arg1)
}

// ListEnterpriseAIUserUsage mocks base method.
func (m *MockBillingServiceHandler) ListEnterpriseAIUserUsage(arg0 context.Context, arg1 *connect.Request[v1.ListEnterpriseAIUserUsageRequest]) (*connect.Response[v1.ListEnterpriseAIUserUsageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnterpriseAIUserUsage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListEnterpriseAIUserUsageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnterpriseAIUserUsage indicates an expected call of ListEnterpriseAIUserUsage.
func (mr *MockBillingServiceHandlerMockRecorder) ListEnterpriseAIUserUsage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnterpriseAIUserUsage", reflect.TypeOf((*MockBillingServiceHandler)(nil).ListEnterpriseAIUserUsage), arg0, arg1)
}

// ListEnterpriseUserCreditUsage mocks base method.
func (m *MockBillingServiceHandler) ListEnterpriseUserCreditUsage(arg0 context.Context, arg1 *connect.Request[v1.ListEnterpriseUserCreditUsageRequest]) (*connect.Response[v1.ListEnterpriseUserCreditUsageResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnterpriseUserCreditUsage", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.ListEnterpriseUserCreditUsageResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnterpriseUserCreditUsage indicates an expected call of ListEnterpriseUserCreditUsage.
func (mr *MockBillingServiceHandlerMockRecorder) ListEnterpriseUserCreditUsage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnterpriseUserCreditUsage", reflect.TypeOf((*MockBillingServiceHandler)(nil).ListEnterpriseUserCreditUsage), arg0, arg1)
}

// SetEnterpriseAIUserBudgetPolicy mocks base method.
func (m *MockBillingServiceHandler) SetEnterpriseAIUserBudgetPolicy(arg0 context.Context, arg1 *connect.Request[v1.SetEnterpriseAIUserBudgetPolicyRequest]) (*connect.Response[v1.SetEnterpriseAIUserBudgetPolicyResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnterpriseAIUserBudgetPolicy", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.SetEnterpriseAIUserBudgetPolicyResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEnterpriseAIUserBudgetPolicy indicates an expected call of SetEnterpriseAIUserBudgetPolicy.
func (mr *MockBillingServiceHandlerMockRecorder) SetEnterpriseAIUserBudgetPolicy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnterpriseAIUserBudgetPolicy", reflect.TypeOf((*MockBillingServiceHandler)(nil).SetEnterpriseAIUserBudgetPolicy), arg0, arg1)
}

// UpdateTeamCreditAllocation mocks base method.
func (m *MockBillingServiceHandler) UpdateTeamCreditAllocation(arg0 context.Context, arg1 *connect.Request[v1.UpdateTeamCreditAllocationRequest]) (*connect.Response[v1.UpdateTeamCreditAllocationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeamCreditAllocation", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[v1.UpdateTeamCreditAllocationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTeamCreditAllocation indicates an expected call of UpdateTeamCreditAllocation.
func (mr *MockBillingServiceHandlerMockRecorder) UpdateTeamCreditAllocation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeamCreditAllocation", reflect.TypeOf((*MockBillingServiceHandler)(nil).UpdateTeamCreditAllocation), arg0, arg1)
}
